### ISSUE TITLE
Zooming to original resolution renders a blurry image (in Chrome and Opera)

### ISSUE THREAD

**Issue by p-4** [kingdido999/zooming#64] opened 2018-03-29 10:55 UTC
Using a version of zooming.js which Miguel has kindly sent to me, I can set the zooming to at most the maximum resolution of the original image. It works and does not zoom past the specified dimensions.

Although this produces a blurry image in both Chrome and Opera.

Sometimes it does, sometimes it does not. I cannot figure out what makes this happen one time and then not another time.

@migueldemoura has seen the demo from the mediafire link and also wrote that he could see the issue.

Please see the codepen here _(currently it does not show blur for me)_:
https://codepen.io/zuhocuyixu/pen/mxXLwR

Files for local test _(currently it is blurry for me)_:
http://www.mediafire.com/file/z338qhdsbnw94fa/zooming_issue.zip

To verify if there is blur, please zoom the image, then right click and open the image in new tab.
Then compare both tabs to see if both images have the same sharpness.

**Comment by kingdido999** [comment] 2018-03-29 22:42
Yes I can tell...But since it only happens in some browsers (Firefox renders sharply), it must be related to how the browser engine renders the image. And I doubt it's introduced by Miguel's change, @p-4 can you confirm it's also blurry on the latest zooming library?

**Comment by migueldemoura** [comment] 2018-03-29 22:45
Yes, as I told @p-4, that's a browser issue (rendered fine on my FF 59).

**Comment by kingdido999** [comment] 2018-04-05 02:24
I will close this issue since it's not a bug related to this library.

**Closed by kingdido999** 2018-04-05 02:24 UTC
Labels: invalid

**Comment by p-4** [comment] 2018-04-05 10:39
@kingdido999 I have just done some more testing and I think I figured what is causing this.

Both within Opera and Chrome I can reproduce the following:
1. Open the browser, resize it so it takes most of the screen, but is not maximized.
2. Open the image in question. It might render a blurry image or not blurry. It seems random.
3. Then I resize the height of the browser window. Then it might render the same or it might render different. The more times I resizes the height the more I get a different result.

From this I think it has to do with the height being odd or an even number.
For example 1200px vs 1201px height of the part of the browser which renders the webpage.

What are your thoughts about this?
My thinking is this has to do with the library and how it renders an image. If it takes into account odd or even number of pixels in height it could circumvent the issue when it detects an odd number.

**Comment by p-4** [comment] 2018-04-06 08:33
@kingdido999 The image I am using in the codepen I posted in the first post has an even number of pixels and you can test the issue as I describe it with it:
https://codepen.io/zuhocuyixu/pen/mxXLwR

1. Unmaximize your browser.
2. Make it so it takes most of the screen ( so the image can be seen at its original resolution )
3. Resize the height of the browser window a couple of times. 

You will see that it sometimes renders sharp image and sometimes blurry.

Can something be done within zooming to avoid this blurry image and always render sharp?

**Comment by migueldemoura** [comment] 2018-04-08 17:59
@p-4, this appears to be a browser issue, FF renders it just fine on my end. You can try it yourself as well, see if you can reproduce it. If you find a workaround/hack that isn't overly complicated, I'm sure @kingdido999 would consider including it.

**Comment by p-4** [comment] 2018-04-09 09:54
I tried FF myself and it does work as it should.

This is disappointing.
To have both Chrome and Opera not display the image as it should be.

I do not have the skill or idea for a workaround or a hack.

**Comment by migueldemoura** [comment] 2018-09-03 19:54
@p-4, @kingdido999 

I got hit by this bug and spent a while figuring out what the cause was.
In my case, having "border-radius" caused the image to be distorted around the top left corner. Another problem (that we were already aware of) is the odd width/height.

Fixes for both issues without touching the source:

``` javascript
new Zooming({
    onBeforeOpen: (e) => e.style['border-radius'] = '0',
    onBeforeClose: (e) => e.style['border-radius'] = ''
});
```

``` javascript
new Zooming({
    onBeforeOpen: (e) => e.height = 2 * Math.round(e.height / 2),
    onBeforeClose: (e) => e.width = 2 * Math.round(e.width / 2)
});
```

Hope that helps :smile:.
